export const diseases = [
  {
    name: "Derrame cerebral",
    category: "cronica",
    causes: "Interrupção ou rompimento do fluxo sanguíneo cerebral, causado por trombos ou hemorragias.",
    symptoms: "Fraqueza em um lado do corpo, dificuldade de fala, visão turva, perda de equilíbrio, dor de cabeça intensa.",
    treatments: "Trombólise, cirurgia, fisioterapia, fonoaudiologia, anticoagulantes, reabilitação.",
    prevention: "Controle da pressão arterial, alimentação saudável, atividade física, não fumar.",
    medicines: [ 
      {
        name: "Ácido acetilsalicílico (AAS)",
        indication: "Prevenção de novos eventos isquêmicos após derrame cerebral.",
        dosage: "100 mg/dia",
        sideEffects: "Sangramentos, irritação gástrica.",
        contraindications: "Úlcera ativa, alergia a salicilatos.",
        therapeuticAction: "Antiplaquetário",
        mechanismOfAction: "Inibe a agregação plaquetária.",
        activeIngredient: "Ácido acetilsalicílico",
        dosageInstructions: "Tomar com alimento.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Comprimido",
        drugInteractions: "Varfarina, ibuprofeno, anticoagulantes.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Ácido acetilsalicílico (AAS)"
      },
      {
        name: "Clopidogrel",
        indication: "Prevenção de eventos trombóticos em pacientes com AVC isquêmico.",
        dosage: "75 mg/dia",
        sideEffects: "Hemorragias, diarreia, dor abdominal.",
        contraindications: "Sangramento ativo, alergia ao clopidogrel.",
        therapeuticAction: "Antiplaquetário",
        mechanismOfAction: "Inibe a agregação plaquetária por bloqueio do receptor P2Y12.",
        activeIngredient: "Clopidogrel",
        dosageInstructions: "Tomar com ou sem alimentos.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Comprimido",
        drugInteractions: "Omeprazol, varfarina, AINEs.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Clopidogrel"
      },
      {
        name: "Varfarina",
        indication: "Prevenção de embolias em pacientes com fibrilação atrial e AVC.",
        dosage: "Individualizado (monitorado por INR)",
        sideEffects: "Sangramentos, necrose cutânea.",
        contraindications: "Gravidez, sangramentos ativos.",
        therapeuticAction: "Anticoagulante oral",
        mechanismOfAction: "Inibe a síntese hepática de fatores de coagulação vitamina K-dependentes.",
        activeIngredient: "Varfarina sódica",
        dosageInstructions: "Tomar no mesmo horário todos os dias.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Comprimido",
        drugInteractions: "Antibióticos, antifúngicos, alimentos ricos em vitamina K.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Varfarina"
      },
      {
        name: "Atorvastatina",
        indication: "Redução do colesterol em pacientes com risco cardiovascular elevado.",
        dosage: "10 a 80 mg/dia",
        sideEffects: "Dor muscular, elevação de enzimas hepáticas.",
        contraindications: "Doença hepática ativa.",
        therapeuticAction: "Estatina (hipolipemiante)",
        mechanismOfAction: "Inibe a HMG-CoA redutase.",
        activeIngredient: "Atorvastatina cálcica",
        dosageInstructions: "Tomar preferencialmente à noite.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Comprimido",
        drugInteractions: "Suco de toranja, claritromicina, antifúngicos.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Atorvastatina"
      },
      {
        name: "Enoxaparina",
        indication: "Prevenção de tromboembolismo venoso em pacientes hospitalizados com AVC.",
        dosage: "40 mg/dia",
        sideEffects: "Sangramentos, trombocitopenia.",
        contraindications: "Sangramento ativo, hipersensibilidade à heparina.",
        therapeuticAction: "Anticoagulante (heparina de baixo peso molecular)",
        mechanismOfAction: "Inibe a trombina e o fator Xa.",
        activeIngredient: "Enoxaparina sódica",
        dosageInstructions: "Aplicar via subcutânea conforme prescrição.",
        administrationRoute: "Subcutânea",
        pharmaceuticalForm: "Solução injetável",
        drugInteractions: "Outros anticoagulantes, AINEs, trombolíticos.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Enoxaparina"
      }
    ]    
  },

  {
    name: "Doença de Alzheimer",
    category: "cronica",
    causes: "Degeneração progressiva dos neurônios, com acúmulo de proteínas beta-amiloide e tau.",
    symptoms: "Perda de memória, confusão mental, dificuldade com tarefas diárias, alterações de humor.",
    treatments: "Medicamentos inibidores da acetilcolinesterase, moduladores glutamatérgicos, estimulação cognitiva.",
    prevention: "Exercício físico, atividades cognitivas, controle de fatores de risco como hipertensão e diabetes.",
    medicines: [
      {
        name: "Donepezila",
        indication: "Tratamento da doença de Alzheimer leve a moderada.",
        dosage: "5 a 10 mg/dia",
        sideEffects: "Náusea, insônia, cãibras musculares.",
        contraindications: "Hipersensibilidade ao donepezila.",
        therapeuticAction: "Inibidor da acetilcolinesterase.",
        mechanismOfAction: "Aumenta a concentração de acetilcolina no cérebro.",
        activeIngredient: "Donepezila",
        dosageInstructions: "Tomar à noite, antes de dormir.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Comprimido",
        drugInteractions: "Anticolinérgicos, cetoconazol, rifampicina.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Donepezila"
      },
      {
        name: "Rivastigmina",
        indication: "Tratamento da doença de Alzheimer leve a moderada.",
        dosage: "1,5 mg 2x/dia, podendo chegar a 6 mg 2x/dia.",
        sideEffects: "Náusea, vômito, perda de apetite.",
        contraindications: "Hipersensibilidade ao fármaco.",
        therapeuticAction: "Inibidor da colinesterase.",
        mechanismOfAction: "Inibe a acetilcolinesterase e a butirilcolinesterase.",
        activeIngredient: "Rivastigmina",
        dosageInstructions: "Tomar com alimentos para reduzir efeitos gastrointestinais.",
        administrationRoute: "Oral ou transdérmica",
        pharmaceuticalForm: "Cápsula ou adesivo",
        drugInteractions: "Metoclopramida, beta-bloqueadores.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Rivastigmina"
      },
      {
        name: "Galantamina",
        indication: "Tratamento de Alzheimer leve a moderado.",
        dosage: "8 mg/dia, aumentando gradualmente até 24 mg/dia.",
        sideEffects: "Distúrbios gastrointestinais, tontura.",
        contraindications: "Doença hepática ou renal grave.",
        therapeuticAction: "Inibidor da acetilcolinesterase.",
        mechanismOfAction: "Aumenta a ação colinérgica e modula receptores nicotínicos.",
        activeIngredient: "Galantamina",
        dosageInstructions: "Tomar com café da manhã e jantar.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Comprimido",
        drugInteractions: "Paroxetina, cetoconazol, atropina.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Galantamina"
      },
      {
        name: "Memantina",
        indication: "Tratamento de Alzheimer moderado a grave.",
        dosage: "5 a 20 mg/dia",
        sideEffects: "Tontura, dor de cabeça, constipação.",
        contraindications: "Hipersensibilidade, insuficiência renal grave.",
        therapeuticAction: "Antagonista do receptor NMDA.",
        mechanismOfAction: "Modula atividade do glutamato no cérebro.",
        activeIngredient: "Memantina",
        dosageInstructions: "Tomar com ou sem alimentos.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Comprimido",
        drugInteractions: "Amantadina, cetamina, bicarbonato de sódio.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Memantina"
      },
      {
        name: "Vitamina E",
        indication: "Suplemento antioxidante usado para retardar progressão da doença.",
        dosage: "1000 IU 2x/dia",
        sideEffects: "Hemorragias em doses elevadas.",
        contraindications: "Distúrbios hemorrágicos.",
        therapeuticAction: "Antioxidante",
        mechanismOfAction: "Neutraliza radicais livres que danificam células nervosas.",
        activeIngredient: "Alfa-tocoferol",
        dosageInstructions: "Tomar com refeição rica em gordura.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Cápsula",
        drugInteractions: "Anticoagulantes orais como varfarina.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Vitamina E"
      }
    ]
  },
  
  {
    name: "Mal de Parkinson",
    category: "cronica",
    causes: "Degeneração progressiva dos neurônios produtores de dopamina na substância negra do cérebro.",
    symptoms: "Tremores em repouso, rigidez muscular, bradicinesia (lentidão dos movimentos), instabilidade postural.",
    treatments: "Terapia medicamentosa, fisioterapia, fonoaudiologia, estimulação cerebral profunda em casos avançados.",
    prevention: "Não existe prevenção específica, mas atividades físicas e alimentação saudável podem ajudar a retardar os sintomas.",
    medicines: [
      {
        name: "Levodopa + Carbidopa",
        indication: "Tratamento de primeira linha para sintomas motores do Parkinson.",
        dosage: "Iniciar com 100/25 mg 3x/dia e ajustar conforme necessário.",
        sideEffects: "Movimentos involuntários, náusea, hipotensão postural.",
        contraindications: "Glaucoma de ângulo fechado, melanoma.",
        therapeuticAction: "Precursor da dopamina com inibidor da descarboxilase periférica.",
        mechanismOfAction: "Aumenta dopamina no cérebro e evita conversão periférica.",
        activeIngredient: "Levodopa + Carbidopa",
        dosageInstructions: "Tomar longe das refeições ricas em proteína.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Comprimido",
        drugInteractions: "Inibidores da MAO, antipsicóticos, ferro.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Levodopa%20Carbidopa"
      },
      {
        name: "Pramipexol",
        indication: "Monoterapia em estágios iniciais ou adjuvante à levodopa.",
        dosage: "0,125 mg 3x/dia, aumentando gradualmente até 1,5 mg 3x/dia.",
        sideEffects: "Sonolência, compulsões, alucinações.",
        contraindications: "Doença renal avançada sem ajuste.",
        therapeuticAction: "Agonista dopaminérgico",
        mechanismOfAction: "Estimula diretamente os receptores de dopamina.",
        activeIngredient: "Pramipexol",
        dosageInstructions: "Tomar com ou sem alimentos.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Comprimido",
        drugInteractions: "Cimetidina, antipsicóticos.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Pramipexol"
      },
      {
        name: "Amantadina",
        indication: "Redução de discinesias causadas por levodopa.",
        dosage: "100 a 300 mg/dia",
        sideEffects: "Inchaço, confusão, livedo reticular.",
        contraindications: "Epilepsia, insuficiência renal grave.",
        therapeuticAction: "Antiviral com ação antiparkinsoniana",
        mechanismOfAction: "Aumenta liberação de dopamina e bloqueia NMDA.",
        activeIngredient: "Amantadina",
        dosageInstructions: "Tomar de manhã para evitar insônia.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Cápsula ou xarope",
        drugInteractions: "Diuréticos, anticolinérgicos.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Amantadina"
      },
      {
        name: "Selegilina",
        indication: "Adjuvante à levodopa para prolongar seus efeitos.",
        dosage: "5 mg 2x/dia",
        sideEffects: "Insônia, agitação, aumento da pressão arterial.",
        contraindications: "Uso concomitante com antidepressivos tricíclicos ou ISRS.",
        therapeuticAction: "Inibidor seletivo da MAO-B",
        mechanismOfAction: "Reduz a degradação da dopamina cerebral.",
        activeIngredient: "Selegilina",
        dosageInstructions: "Evitar tomar após 16h para prevenir insônia.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Comprimido",
        drugInteractions: "ISRS, antidepressivos tricíclicos, petidina.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Selegilina"
      },
      {
        name: "Entacapona",
        indication: "Prolonga efeito da levodopa em pacientes com flutuação motora.",
        dosage: "200 mg com cada dose de levodopa (até 8x/dia)",
        sideEffects: "Urina avermelhada, diarreia, discinesia.",
        contraindications: "Doença hepática grave.",
        therapeuticAction: "Inibidor da COMT",
        mechanismOfAction: "Inibe degradação periférica da levodopa.",
        activeIngredient: "Entacapona",
        dosageInstructions: "Sempre associada à levodopa.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Comprimido",
        drugInteractions: "Rifampicina, inibidores da MAO.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Entacapona"
      }
    ]
  },  

  {
    name: "DPOC",
    category: "cronica",
    causes: "Exposição crônica à fumaça do cigarro, poluição ambiental ou ocupacional.",
    symptoms: "Falta de ar, tosse crônica, produção de muco, chiado no peito.",
    treatments: "Broncodilatadores de curta e longa duração, corticosteroides inalatórios, reabilitação pulmonar, oxigenoterapia.",
    prevention: "Parar de fumar, evitar ambientes poluídos, vacinação contra gripe e pneumonia.",
    medicines: [
      {
        name: "Salbutamol",
        indication: "Alívio rápido de broncoespasmo.",
        dosage: "100 mcg por inalação, até 4x/dia.",
        sideEffects: "Tremores, taquicardia, nervosismo.",
        contraindications: "Cardiopatias graves, hipertireoidismo.",
        therapeuticAction: "Broncodilatador beta-2 agonista de curta duração (SABA)",
        mechanismOfAction: "Relaxamento do músculo liso brônquico.",
        activeIngredient: "Salbutamol",
        dosageInstructions: "Usar conforme necessidade.",
        administrationRoute: "Inalatória",
        pharmaceuticalForm: "Spray (MDI)",
        drugInteractions: "Beta-bloqueadores, diuréticos, teofilina.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Salbutamol"
      },
      {
        name: "Tiotrópio",
        indication: "Tratamento de manutenção da DPOC.",
        dosage: "1 cápsula (18 mcg) 1x/dia por inalação.",
        sideEffects: "Boca seca, constipação, retenção urinária.",
        contraindications: "Alergia a anticolinérgicos.",
        therapeuticAction: "Anticolinérgico de longa duração (LAMA)",
        mechanismOfAction: "Bloqueia receptores muscarínicos no pulmão.",
        activeIngredient: "Tiotrópio",
        dosageInstructions: "Usar diariamente, sempre no mesmo horário.",
        administrationRoute: "Inalatória",
        pharmaceuticalForm: "Cápsula para inalação",
        drugInteractions: "Outros anticolinérgicos.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Tiotrópio"
      },
      {
        name: "Formoterol",
        indication: "Broncodilatação de longa duração para DPOC.",
        dosage: "12 mcg 2x/dia por inalação.",
        sideEffects: "Palpitações, dor de cabeça, cãibras.",
        contraindications: "Arritmias, hipersensibilidade.",
        therapeuticAction: "Beta-2 agonista de longa duração (LABA)",
        mechanismOfAction: "Relaxamento prolongado da musculatura brônquica.",
        activeIngredient: "Formoterol",
        dosageInstructions: "Usar regularmente mesmo sem sintomas.",
        administrationRoute: "Inalatória",
        pharmaceuticalForm: "Inalador em pó",
        drugInteractions: "Diuréticos, betabloqueadores.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Formoterol"
      },
      {
        name: "Budesonida",
        indication: "Controle da inflamação em casos mais graves.",
        dosage: "200 a 400 mcg 2x/dia.",
        sideEffects: "Rouquidão, candidíase oral.",
        contraindications: "Tuberculose pulmonar ativa.",
        therapeuticAction: "Corticosteroide inalatório (ICS)",
        mechanismOfAction: "Reduz inflamação das vias aéreas.",
        activeIngredient: "Budesonida",
        dosageInstructions: "Enxaguar a boca após o uso.",
        administrationRoute: "Inalatória",
        pharmaceuticalForm: "Spray ou pó inalatório",
        drugInteractions: "Ritonavir, cetoconazol.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Budesonida"
      },
      {
        name: "Roflumilaste",
        indication: "Redução de exacerbações em DPOC grave com bronquite crônica.",
        dosage: "500 mcg 1x/dia",
        sideEffects: "Perda de peso, diarreia, insônia.",
        contraindications: "Doenças hepáticas graves.",
        therapeuticAction: "Inibidor da fosfodiesterase-4 (PDE-4)",
        mechanismOfAction: "Reduz a inflamação pulmonar.",
        activeIngredient: "Roflumilaste",
        dosageInstructions: "Tomar com ou sem alimentos.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Comprimido",
        drugInteractions: "Teofilina, fluvoxamina, eritromicina.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Roflumilaste"
      }
    ]
  },  
  
  {
    name: "Asma",
    category: "cronica",
    causes: "Inflamação crônica das vias aéreas, geralmente de origem alérgica ou ambiental.",
    symptoms: "Falta de ar, tosse, chiado no peito, sensação de aperto no tórax.",
    treatments: "Corticosteroides inalados, broncodilatadores, controle ambiental, imunoterapia em alguns casos.",
    prevention: "Evitar alérgenos conhecidos, manter boa higiene, vacinação, e seguir tratamento contínuo.",
    medicines: [
      {
        name: "Budesonida",
        indication: "Controle de manutenção da asma persistente.",
        dosage: "200–400 mcg 2x/dia.",
        sideEffects: "Rouquidão, candidíase oral.",
        contraindications: "Tuberculose pulmonar ativa.",
        therapeuticAction: "Corticosteroide inalatório (ICS)",
        mechanismOfAction: "Reduz inflamação das vias aéreas.",
        activeIngredient: "Budesonida",
        dosageInstructions: "Enxaguar a boca após o uso.",
        administrationRoute: "Inalatória",
        pharmaceuticalForm: "Spray ou pó inalatório",
        drugInteractions: "Ritonavir, cetoconazol.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Budesonida"
      },
      {
        name: "Salbutamol",
        indication: "Alívio rápido de sintomas agudos de broncoespasmo.",
        dosage: "100 mcg por inalação a cada 4-6 horas.",
        sideEffects: "Tremores, taquicardia, nervosismo.",
        contraindications: "Hipersensibilidade, cardiopatias graves.",
        therapeuticAction: "Beta-2 agonista de curta duração (SABA)",
        mechanismOfAction: "Relaxamento da musculatura lisa brônquica.",
        activeIngredient: "Salbutamol",
        dosageInstructions: "Usar somente em crises ou antes de exercícios.",
        administrationRoute: "Inalatória",
        pharmaceuticalForm: "Spray",
        drugInteractions: "Diuréticos, beta-bloqueadores, teofilina.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Salbutamol"
      },
      {
        name: "Formoterol",
        indication: "Controle de longo prazo da asma quando associado a ICS.",
        dosage: "12 mcg 2x/dia.",
        sideEffects: "Palpitações, insônia, dor de cabeça.",
        contraindications: "Monoterapia em asma, hipersensibilidade.",
        therapeuticAction: "Beta-2 agonista de longa duração (LABA)",
        mechanismOfAction: "Broncodilatação prolongada.",
        activeIngredient: "Formoterol",
        dosageInstructions: "Sempre associado a corticosteroide.",
        administrationRoute: "Inalatória",
        pharmaceuticalForm: "Inalador de pó seco",
        drugInteractions: "Teofilina, antidepressivos tricíclicos.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Formoterol"
      },
      {
        name: "Montelucaste",
        indication: "Controle da asma leve persistente ou alérgica.",
        dosage: "10 mg à noite.",
        sideEffects: "Dor abdominal, dor de cabeça, alterações de humor.",
        contraindications: "Hipersensibilidade ao fármaco.",
        therapeuticAction: "Antagonista de receptores de leucotrienos.",
        mechanismOfAction: "Reduz a inflamação e o broncoespasmo induzido por alérgenos.",
        activeIngredient: "Montelucaste de sódio",
        dosageInstructions: "Tomar uma vez ao dia, à noite.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Comprimido",
        drugInteractions: "Fenobarbital, rifampicina.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Montelucaste"
      },
      {
        name: "Fluticasona + Salmeterol",
        indication: "Tratamento de asma moderada a grave.",
        dosage: "125/25 mcg ou 250/50 mcg, 2x/dia.",
        sideEffects: "Rouquidão, candidíase oral, tremores.",
        contraindications: "Hipersensibilidade, uso isolado em crises.",
        therapeuticAction: "Corticosteroide + broncodilatador de longa duração (ICS + LABA)",
        mechanismOfAction: "Redução da inflamação e broncodilatação sustentada.",
        activeIngredient: "Fluticasona + Salmeterol",
        dosageInstructions: "Usar diariamente, mesmo sem sintomas.",
        administrationRoute: "Inalatória",
        pharmaceuticalForm: "Spray de pó seco",
        drugInteractions: "Beta-bloqueadores, ritonavir, cetoconazol.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Fluticasona%20Salmeterol"
      }
    ]
  },  
  
  {
    name: "Colesterol Alto",
    category: "cronica",
    causes: "Alimentação rica em gorduras saturadas e trans, sedentarismo, obesidade, predisposição genética.",
    symptoms: "Assintomático na maioria dos casos; pode levar a doenças cardiovasculares como infarto e AVC.",
    treatments: "Mudança no estilo de vida, dieta balanceada, prática de exercícios físicos, e medicamentos hipolipemiantes.",
    prevention: "Dieta equilibrada, atividade física regular, controle do peso, abandono do tabagismo.",
    medicines: [
      {
        name: "Sinvastatina",
        indication: "Redução de colesterol LDL e prevenção de eventos cardiovasculares.",
        dosage: "10 a 40 mg à noite.",
        sideEffects: "Dor muscular, alteração das enzimas hepáticas.",
        contraindications: "Doença hepática ativa, gravidez.",
        therapeuticAction: "Inibidor da HMG-CoA redutase (estatina)",
        mechanismOfAction: "Reduz a síntese hepática de colesterol.",
        activeIngredient: "Sinvastatina",
        dosageInstructions: "Tomar à noite.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Comprimido",
        drugInteractions: "Suco de toranja, cetoconazol, ciclosporina.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Sinvastatina"
      },
      {
        name: "Atorvastatina",
        indication: "Tratamento da dislipidemia e prevenção de doenças cardiovasculares.",
        dosage: "10 a 80 mg/dia.",
        sideEffects: "Mialgia, elevação das enzimas hepáticas.",
        contraindications: "Gravidez, doença hepática.",
        therapeuticAction: "Estatina (hipolipemiante)",
        mechanismOfAction: "Inibe a HMG-CoA redutase, enzima-chave na síntese de colesterol.",
        activeIngredient: "Atorvastatina",
        dosageInstructions: "Pode ser tomada a qualquer hora do dia.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Comprimido",
        drugInteractions: "Verapamil, amiodarona, antifúngicos azólicos.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Atorvastatina"
      },
      {
        name: "Rosuvastatina",
        indication: "Redução eficaz de LDL e aumento do HDL.",
        dosage: "5 a 40 mg/dia.",
        sideEffects: "Fraqueza, dor muscular, constipação.",
        contraindications: "Insuficiência hepática, gravidez.",
        therapeuticAction: "Estatina potente",
        mechanismOfAction: "Inibição competitiva da HMG-CoA redutase.",
        activeIngredient: "Rosuvastatina",
        dosageInstructions: "Pode ser tomada em qualquer horário.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Comprimido",
        drugInteractions: "Antiácidos, ciclosporina, fibratos.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Rosuvastatina"
      },
      {
        name: "Ezetimiba",
        indication: "Redução do colesterol quando estatinas não são suficientes ou são contraindicadas.",
        dosage: "10 mg/dia.",
        sideEffects: "Dor abdominal, fadiga, diarreia.",
        contraindications: "Doença hepática moderada a grave.",
        therapeuticAction: "Inibidor da absorção de colesterol",
        mechanismOfAction: "Inibe a proteína NPC1L1 no intestino.",
        activeIngredient: "Ezetimiba",
        dosageInstructions: "Tomar com ou sem alimentos.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Comprimido",
        drugInteractions: "Ciclosporina, colestiramina.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Ezetimiba"
      },
      {
        name: "Fenofibrato",
        indication: "Tratamento de hipertrigliceridemia isolada ou associada ao LDL elevado.",
        dosage: "160 mg/dia.",
        sideEffects: "Distúrbios gastrointestinais, elevação das enzimas hepáticas.",
        contraindications: "Doença hepática ou renal grave.",
        therapeuticAction: "Fibrato (regulador lipídico)",
        mechanismOfAction: "Ativa o receptor PPAR-alfa, aumentando a oxidação dos ácidos graxos.",
        activeIngredient: "Fenofibrato",
        dosageInstructions: "Tomar com alimentos.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Comprimido",
        drugInteractions: "Estatinas, anticoagulantes orais.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Fenofibrato"
      }
    ]
  },
  
  {
    name: "Diabetes",
    category: "cronica",
    causes: "Falta de insulina (tipo 1) ou resistência à insulina (tipo 2), com forte componente genético e ambiental.",
    symptoms: "Sede excessiva, urina frequente, perda de peso, fome constante, visão embaçada, cansaço.",
    treatments: "Mudanças no estilo de vida, medicamentos orais, insulina, controle glicêmico e monitoramento contínuo.",
    prevention: "Para tipo 2: alimentação saudável, prática de exercícios, controle de peso e glicemia.",
    medicines: [
      {
        name: "Metformina",
        indication: "Tratamento inicial para diabetes tipo 2.",
        dosage: "500 a 2000 mg/dia.",
        sideEffects: "Desconforto gastrointestinal, acidose láctica (rara).",
        contraindications: "Insuficiência renal, acidose metabólica.",
        therapeuticAction: "Antidiabético oral (biguanida)",
        mechanismOfAction: "Reduz produção hepática de glicose e melhora sensibilidade à insulina.",
        activeIngredient: "Metformina",
        dosageInstructions: "Tomar com alimentos para reduzir efeitos colaterais.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Comprimido",
        drugInteractions: "Álcool, contraste iodado.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Metformina"
      },
      {
        name: "Insulina NPH",
        indication: "Tratamento do diabetes tipo 1 e tipo 2 quando há falha de controle com orais.",
        dosage: "Individualizada conforme glicemia.",
        sideEffects: "Hipoglicemia, ganho de peso.",
        contraindications: "Alergia à insulina humana.",
        therapeuticAction: "Hormônio hipoglicemiante de ação intermediária.",
        mechanismOfAction: "Facilita entrada de glicose nas células.",
        activeIngredient: "Insulina humana NPH",
        dosageInstructions: "Aplicar antes das refeições ou à noite.",
        administrationRoute: "Subcutânea",
        pharmaceuticalForm: "Solução injetável",
        drugInteractions: "Beta-bloqueadores, álcool.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Insulina NPH"
      },
      {
        name: "Gliclazida",
        indication: "Tratamento de diabetes tipo 2 em pacientes não obesos.",
        dosage: "30 a 120 mg/dia.",
        sideEffects: "Hipoglicemia, ganho de peso.",
        contraindications: "Diabetes tipo 1, insuficiência renal/hepática.",
        therapeuticAction: "Sulfonilureia (antidiabético oral)",
        mechanismOfAction: "Estimula secreção de insulina pelo pâncreas.",
        activeIngredient: "Gliclazida",
        dosageInstructions: "Tomar antes das refeições.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Comprimido",
        drugInteractions: "Beta-bloqueadores, álcool, anticoagulantes orais.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Gliclazida"
      },
      {
        name: "Dapagliflozina",
        indication: "Tratamento de diabetes tipo 2 (também usada em IC e DRC).",
        dosage: "10 mg/dia.",
        sideEffects: "Infecção urinária, desidratação, hipoglicemia.",
        contraindications: "TFR < 30 mL/min, cetose.",
        therapeuticAction: "Inibidor de SGLT2",
        mechanismOfAction: "Aumenta excreção renal de glicose.",
        activeIngredient: "Dapagliflozina",
        dosageInstructions: "Tomar pela manhã.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Comprimido",
        drugInteractions: "Diuréticos, insulina, sulfonilureias.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Dapagliflozina"
      },
      {
        name: "Semaglutida",
        indication: "Controle glicêmico em diabetes tipo 2 com benefício cardiovascular.",
        dosage: "0,25 mg a 1 mg 1x/semana (injeção).",
        sideEffects: "Náusea, vômito, constipação.",
        contraindications: "Histórico pessoal/familiar de carcinoma medular de tireoide.",
        therapeuticAction: "Agonista do GLP-1",
        mechanismOfAction: "Estimula secreção de insulina e reduz esvaziamento gástrico.",
        activeIngredient: "Semaglutida",
        dosageInstructions: "Aplicar sempre no mesmo dia da semana.",
        administrationRoute: "Subcutânea",
        pharmaceuticalForm: "Caneta injetável",
        drugInteractions: "Insulina, outros hipoglicemiantes.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Semaglutida"
      }
    ]
  },  
  
  {
    name: "Hipertensão",
    category: "cronica",
    causes: "Fatores genéticos, consumo excessivo de sal, sedentarismo, obesidade, estresse, alcoolismo.",
    symptoms: "Geralmente assintomática; em casos graves pode causar dor de cabeça, visão embaçada, tontura.",
    treatments: "Redução do sal na dieta, atividade física, controle de peso, uso contínuo de medicamentos.",
    prevention: "Hábitos saudáveis, evitar tabagismo e álcool, alimentação equilibrada, controle do estresse.",
    medicines: [
      {
        name: "Losartana",
        indication: "Tratamento da hipertensão arterial e proteção renal em diabéticos.",
        dosage: "50 a 100 mg/dia.",
        sideEffects: "Tontura, aumento do potássio, hipotensão.",
        contraindications: "Gravidez, insuficiência renal grave.",
        therapeuticAction: "Antagonista dos receptores de angiotensina II (ARA II)",
        mechanismOfAction: "Promove vasodilatação e reduz secreção de aldosterona.",
        activeIngredient: "Losartana potássica",
        dosageInstructions: "Tomar 1x ao dia.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Comprimido",
        drugInteractions: "Diuréticos poupadores de potássio, lítio, AINEs.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Losartana"
      },
      {
        name: "Enalapril",
        indication: "Hipertensão, insuficiência cardíaca.",
        dosage: "10 a 40 mg/dia.",
        sideEffects: "Tosse seca, tontura, aumento de potássio.",
        contraindications: "Gravidez, angioedema prévio.",
        therapeuticAction: "Inibidor da enzima conversora de angiotensina (IECA)",
        mechanismOfAction: "Reduz formação de angiotensina II, causando vasodilatação.",
        activeIngredient: "Enalapril maleato",
        dosageInstructions: "Tomar com ou sem alimentos.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Comprimido",
        drugInteractions: "Diuréticos, potássio, lítio.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Enalapril"
      },
      {
        name: "Amlodipino",
        indication: "Hipertensão e angina do peito.",
        dosage: "5 a 10 mg/dia.",
        sideEffects: "Inchaço, dor de cabeça, rubor facial.",
        contraindications: "Hipotensão grave.",
        therapeuticAction: "Bloqueador dos canais de cálcio (BCC)",
        mechanismOfAction: "Impede entrada de cálcio nas células musculares lisas vasculares.",
        activeIngredient: "Amlodipino besilato",
        dosageInstructions: "Tomar 1x ao dia, no mesmo horário.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Comprimido",
        drugInteractions: "Cimetidina, cetoconazol, sinvastatina.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Amlodipino"
      },
      {
        name: "Hidroclorotiazida",
        indication: "Hipertensão e retenção de líquidos.",
        dosage: "12,5 a 25 mg/dia.",
        sideEffects: "Hipocalemia, aumento de glicemia, gota.",
        contraindications: "Anúria, hipersensibilidade a sulfonamidas.",
        therapeuticAction: "Diurético tiazídico",
        mechanismOfAction: "Inibe reabsorção de sódio e água no túbulo distal renal.",
        activeIngredient: "Hidroclorotiazida",
        dosageInstructions: "Tomar pela manhã.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Comprimido",
        drugInteractions: "Lítio, AINEs, digoxina.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Hidroclorotiazida"
      },
      {
        name: "Clortalidona",
        indication: "Hipertensão essencial, geralmente em combinação.",
        dosage: "12,5 a 50 mg/dia.",
        sideEffects: "Distúrbios hidroeletrolíticos, fadiga.",
        contraindications: "Anúria, hipersensibilidade.",
        therapeuticAction: "Diurético tiazídico de longa duração",
        mechanismOfAction: "Promove diurese e vasodilatação.",
        activeIngredient: "Clortalidona",
        dosageInstructions: "Preferencialmente pela manhã.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Comprimido",
        drugInteractions: "AINEs, lítio, antidiabéticos orais.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Clortalidona"
      }
    ]
  },    

  {
    name: "Tracoma",
    category: "negligenciada",
    causes: "Infecção ocular causada pela bactéria *Chlamydia trachomatis*, transmitida por contato direto ou vetores como moscas.",
    symptoms: "Coceira nos olhos, secreção, dor ocular, pálpebras inchadas, em casos avançados pode causar cegueira.",
    treatments: "Antibióticos tópicos e orais, higiene pessoal, cirurgia em casos de complicações.",
    prevention: "Lavar o rosto regularmente, acesso à água potável, controle de moscas e saneamento.",
    medicines: [
      {
        name: "Azitromicina",
        indication: "Tratamento sistêmico do tracoma ativo.",
        dosage: "Dose única de 20 mg/kg (máx. 1 g).",
        sideEffects: "Náuseas, dor abdominal, diarreia.",
        contraindications: "Hipersensibilidade a macrolídeos.",
        therapeuticAction: "Antibiótico macrolídeo.",
        mechanismOfAction: "Inibe a síntese proteica bacteriana.",
        activeIngredient: "Azitromicina",
        dosageInstructions: "Dose única oral conforme peso.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Comprimido ou suspensão oral",
        drugInteractions: "Varfarina, antiácidos, digoxina.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Azitromicina"
      },
      {
        name: "Tetraciclina oftálmica",
        indication: "Tratamento local do tracoma.",
        dosage: "Aplicar 2x/dia por 6 semanas.",
        sideEffects: "Irritação ocular leve.",
        contraindications: "Crianças < 8 anos, gravidez.",
        therapeuticAction: "Antibiótico tetraciclina.",
        mechanismOfAction: "Inibe síntese proteica bacteriana.",
        activeIngredient: "Tetraciclina",
        dosageInstructions: "Aplicar na pálpebra inferior.",
        administrationRoute: "Tópica ocular",
        pharmaceuticalForm: "Pomada oftálmica",
        drugInteractions: "Nenhuma significativa via tópica.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Tetraciclina"
      },
      {
        name: "Eritromicina oral",
        indication: "Alternativa à azitromicina em crianças pequenas.",
        dosage: "50 mg/kg/dia dividido em 4 doses por 14 dias.",
        sideEffects: "Distúrbios gastrointestinais.",
        contraindications: "Doença hepática ativa.",
        therapeuticAction: "Antibiótico macrolídeo.",
        mechanismOfAction: "Inibe síntese de proteínas bacterianas.",
        activeIngredient: "Eritromicina",
        dosageInstructions: "Tomar com o estômago vazio.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Suspensão ou comprimido",
        drugInteractions: "Teofilina, varfarina.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Eritromicina"
      },
      {
        name: "Doxiciclina",
        indication: "Tratamento de adultos com tracoma ativo.",
        dosage: "100 mg 2x/dia por 7 dias.",
        sideEffects: "Fotossensibilidade, distúrbios digestivos.",
        contraindications: "Gravidez, crianças < 8 anos.",
        therapeuticAction: "Antibiótico tetraciclina.",
        mechanismOfAction: "Inibição da síntese proteica bacteriana.",
        activeIngredient: "Doxiciclina",
        dosageInstructions: "Evitar exposição solar intensa.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Comprimido",
        drugInteractions: "Anticoagulantes, lítio, anticoncepcionais orais.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Doxiciclina"
      },
      {
        name: "Cloranfenicol colírio",
        indication: "Adjuvante no controle de infecções oculares bacterianas.",
        dosage: "1 a 2 gotas a cada 4-6 horas.",
        sideEffects: "Irritação ocular leve, reações alérgicas.",
        contraindications: "Histórico de aplasia medular.",
        therapeuticAction: "Antibiótico bacteriostático.",
        mechanismOfAction: "Inibe a síntese proteica bacteriana.",
        activeIngredient: "Cloranfenicol",
        dosageInstructions: "Aplicar conforme prescrição.",
        administrationRoute: "Tópica ocular",
        pharmaceuticalForm: "Colírio",
        drugInteractions: "Fenobarbital, rifampicina.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Cloranfenicol"
      }
    ]
  },
  
  {
    name: "Doença de Chagas",
    category: "negligenciada",
    causes: "Infecção causada pelo protozoário *Trypanosoma cruzi*, transmitida principalmente pelo inseto barbeiro.",
    symptoms: "Febre, mal-estar, inchaço no local da picada (fase aguda); insuficiência cardíaca, distúrbios digestivos (fase crônica).",
    treatments: "Antiparasitários na fase aguda, tratamento sintomático e suporte clínico na fase crônica.",
    prevention: "Melhoria de habitações, controle do vetor, triagem em doações de sangue e órgãos.",
    medicines: [
      {
        name: "Benznidazol",
        indication: "Tratamento da fase aguda da doença de Chagas.",
        dosage: "5 a 7 mg/kg/dia por 60 dias.",
        sideEffects: "Erupções cutâneas, neuropatia, dor abdominal.",
        contraindications: "Hipersensibilidade ao fármaco.",
        therapeuticAction: "Antiparasitário nitroimidazólico.",
        mechanismOfAction: "Forma radicais livres que danificam o DNA do parasita.",
        activeIngredient: "Benznidazol",
        dosageInstructions: "Tomar com alimentos.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Comprimido",
        drugInteractions: "Álcool, imunossupressores, medicamentos hepatotóxicos.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Benznidazol"
      },
      {
        name: "Nifurtimox",
        indication: "Alternativa ao benznidazol no tratamento da doença de Chagas.",
        dosage: "8 a 10 mg/kg/dia por 60 dias.",
        sideEffects: "Perda de apetite, vômitos, convulsões.",
        contraindications: "Gravidez, distúrbios neurológicos.",
        therapeuticAction: "Antiparasitário.",
        mechanismOfAction: "Produz radicais livres tóxicos ao parasita.",
        activeIngredient: "Nifurtimox",
        dosageInstructions: "Tomar com alimentos, fracionado.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Comprimido",
        drugInteractions: "Álcool, medicamentos neurotóxicos.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Nifurtimox"
      },
      {
        name: "Amiodarona",
        indication: "Tratamento de arritmias cardíacas associadas à fase crônica.",
        dosage: "200 a 400 mg/dia.",
        sideEffects: "Alterações da tireoide, fotossensibilidade, toxicidade pulmonar.",
        contraindications: "Bradicardia severa, bloqueios AV.",
        therapeuticAction: "Antiarrítmico classe III.",
        mechanismOfAction: "Bloqueia canais de potássio, prolongando o potencial de ação cardíaco.",
        activeIngredient: "Amiodarona",
        dosageInstructions: "Tomar com alimentos para reduzir irritação gástrica.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Comprimido",
        drugInteractions: "Digoxina, varfarina, betabloqueadores.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Amiodarona"
      },
      {
        name: "Enalapril",
        indication: "Tratamento de insuficiência cardíaca causada pela forma crônica da doença.",
        dosage: "10 a 40 mg/dia.",
        sideEffects: "Tosse, tontura, hiperpotassemia.",
        contraindications: "Gravidez, estenose bilateral de artéria renal.",
        therapeuticAction: "Inibidor da ECA",
        mechanismOfAction: "Reduz vasoconstrição e pós-carga cardíaca.",
        activeIngredient: "Enalapril",
        dosageInstructions: "Tomar de manhã.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Comprimido",
        drugInteractions: "Diuréticos, potássio, lítio.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Enalapril"
      },
      {
        name: "Espironolactona",
        indication: "Adjuvante no tratamento da insuficiência cardíaca refratária.",
        dosage: "25 a 100 mg/dia.",
        sideEffects: "Hipercalemia, ginecomastia.",
        contraindications: "Insuficiência renal grave.",
        therapeuticAction: "Diurético poupador de potássio.",
        mechanismOfAction: "Antagonista da aldosterona nos túbulos renais.",
        activeIngredient: "Espironolactona",
        dosageInstructions: "Tomar após refeições.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Comprimido",
        drugInteractions: "IECA, ARA-II, potássio.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Espironolactona"
      }
    ]
  },  
  
  {
    name: "Hanseníase",
    category: "negligenciada",
    causes: "Infecção crônica causada pela bactéria *Mycobacterium leprae*, transmitida por vias respiratórias.",
    symptoms: "Manchas esbranquiçadas ou avermelhadas com perda de sensibilidade, formigamento, fraqueza muscular, lesões nervosas.",
    treatments: "Poliquimioterapia (PQT) com associação de antibióticos específicos conforme a forma clínica (paucibacilar ou multibacilar).",
    prevention: "Diagnóstico precoce, tratamento dos casos, vacinação BCG para contatos próximos.",
    medicines: [
      {
        name: "Rifampicina",
        indication: "Principal antibiótico bactericida contra o *Mycobacterium leprae*.",
        dosage: "600 mg 1x/mês (dose supervisionada).",
        sideEffects: "Urina avermelhada, hepatotoxicidade, náuseas.",
        contraindications: "Doença hepática ativa.",
        therapeuticAction: "Antibiótico bactericida.",
        mechanismOfAction: "Inibe a RNA polimerase dependente de DNA.",
        activeIngredient: "Rifampicina",
        dosageInstructions: "Tomar em jejum para melhor absorção.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Cápsula",
        drugInteractions: "Anticoncepcionais, anticoagulantes, antirretrovirais.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Rifampicina"
      },
      {
        name: "Dapsona",
        indication: "Tratamento de hanseníase paucibacilar e multibacilar.",
        dosage: "100 mg/dia.",
        sideEffects: "Anemia hemolítica, erupções cutâneas.",
        contraindications: "Deficiência de G6PD, anemia grave.",
        therapeuticAction: "Bacteriostático sulfonado.",
        mechanismOfAction: "Inibe a síntese de ácido fólico bacteriano.",
        activeIngredient: "Dapsona",
        dosageInstructions: "Tomar diariamente.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Comprimido",
        drugInteractions: "Rifampicina, probenecida.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Dapsona"
      },
      {
        name: "Clofazimina",
        indication: "Adjuvante no esquema multibacilar.",
        dosage: "50 mg/dia + 300 mg/mês (supervisionado).",
        sideEffects: "Pigmentação da pele e urina, ressecamento da pele.",
        contraindications: "Hipersensibilidade à substância.",
        therapeuticAction: "Antibiótico antimicobacteriano.",
        mechanismOfAction: "Atua na parede celular e DNA do *Mycobacterium leprae*.",
        activeIngredient: "Clofazimina",
        dosageInstructions: "Tomar com alimentos para reduzir efeitos gastrointestinais.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Cápsula",
        drugInteractions: "Outros medicamentos hepatotóxicos.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Clofazimina"
      },
      {
        name: "Talidomida",
        indication: "Tratamento das reações hansênicas tipo 2 (Eritema Nodoso).",
        dosage: "100 a 300 mg/dia.",
        sideEffects: "Sonolência, neuropatia, teratogenicidade.",
        contraindications: "Gravidez (extremamente contraindicado).",
        therapeuticAction: "Imunomodulador e anti-inflamatório.",
        mechanismOfAction: "Inibe TNF-alfa e modula resposta inflamatória.",
        activeIngredient: "Talidomida",
        dosageInstructions: "Tomar à noite, com orientação médica rigorosa.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Comprimido",
        drugInteractions: "Sedativos, álcool, medicamentos neurotóxicos.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Talidomida"
      },
      {
        name: "Prednisona",
        indication: "Tratamento das reações hansênicas tipo 1 (neurite).",
        dosage: "40 a 60 mg/dia, com redução gradual.",
        sideEffects: "Ganho de peso, insônia, hipertensão.",
        contraindications: "Infecções fúngicas sistêmicas, úlcera ativa.",
        therapeuticAction: "Corticosteroide sistêmico.",
        mechanismOfAction: "Reduz inflamação e resposta imune.",
        activeIngredient: "Prednisona",
        dosageInstructions: "Tomar pela manhã com alimentos.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Comprimido",
        drugInteractions: "AINEs, anticoagulantes, antidiabéticos.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Prednisona"
      }
    ]
  },  
        
  {
    name: "Tuberculose",
    category: "negligenciada",
    causes: "Infecção pulmonar causada pelo *Mycobacterium tuberculosis*, transmitida por via aérea.",
    symptoms: "Tosse persistente por mais de 3 semanas, febre, suor noturno, perda de peso, fadiga.",
    treatments: "Esquema padrão com antibióticos combinados por no mínimo 6 meses, com acompanhamento supervisionado (DOTS).",
    prevention: "Vacina BCG na infância, diagnóstico precoce, tratamento adequado de casos ativos.",
    medicines: [
      {
        name: "Isoniazida",
        indication: "Tratamento de tuberculose ativa e profilaxia.",
        dosage: "5 mg/kg/dia (máx. 300 mg/dia).",
        sideEffects: "Hepatotoxicidade, neuropatia periférica.",
        contraindications: "Doença hepática grave.",
        therapeuticAction: "Antituberculoso bacteriostático.",
        mechanismOfAction: "Inibe a síntese do ácido micólico da parede celular do bacilo.",
        activeIngredient: "Isoniazida",
        dosageInstructions: "Tomar em jejum, evitar álcool.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Comprimido",
        drugInteractions: "Fenitoína, álcool, carbamazepina.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Isoniazida"
      },
      {
        name: "Rifampicina",
        indication: "Parte essencial do esquema básico contra TB.",
        dosage: "10 mg/kg/dia (máx. 600 mg/dia).",
        sideEffects: "Coloração avermelhada de secreções, náuseas, hepatite medicamentosa.",
        contraindications: "Doença hepática ativa, alergia ao fármaco.",
        therapeuticAction: "Antibiótico bactericida.",
        mechanismOfAction: "Inibe a RNA polimerase dependente de DNA.",
        activeIngredient: "Rifampicina",
        dosageInstructions: "Tomar em jejum, longe de outros medicamentos.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Cápsula",
        drugInteractions: "Anticoncepcionais, antirretrovirais, anticoagulantes.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Rifampicina"
      },
      {
        name: "Pirazinamida",
        indication: "Tratamento da fase intensiva da tuberculose.",
        dosage: "20 a 35 mg/kg/dia (máx. 2 g).",
        sideEffects: "Hepatotoxicidade, hiperuricemia, artralgias.",
        contraindications: "Doença hepática grave, gota ativa.",
        therapeuticAction: "Bactericida em meio ácido.",
        mechanismOfAction: "Desorganiza o metabolismo energético do bacilo.",
        activeIngredient: "Pirazinamida",
        dosageInstructions: "Tomar em jejum.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Comprimido",
        drugInteractions: "Alopurinol, rifampicina.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Pirazinamida"
      },
      {
        name: "Etambutol",
        indication: "Componente da fase intensiva do tratamento da TB.",
        dosage: "15 a 25 mg/kg/dia.",
        sideEffects: "Neurite óptica reversível (visão borrada ou alteração de cores).",
        contraindications: "Neurite óptica prévia, crianças pequenas.",
        therapeuticAction: "Bacteriostático.",
        mechanismOfAction: "Inibe a síntese da parede celular do bacilo.",
        activeIngredient: "Etambutol",
        dosageInstructions: "Tomar em jejum, com acompanhamento oftalmológico.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Comprimido",
        drugInteractions: "Antiácidos reduzem absorção.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Etambutol"
      },
      {
        name: "Estreptomicina",
        indication: "Usado em casos resistentes ou em TB meníngea.",
        dosage: "15 mg/kg/dia IM (máx. 1 g/dia).",
        sideEffects: "Ototoxicidade, nefrotoxicidade.",
        contraindications: "Gravidez, insuficiência renal grave.",
        therapeuticAction: "Aminoglicosídeo bactericida.",
        mechanismOfAction: "Inibe síntese proteica bacteriana.",
        activeIngredient: "Estreptomicina",
        dosageInstructions: "Aplicação intramuscular sob supervisão.",
        administrationRoute: "Intramuscular",
        pharmaceuticalForm: "Pó para reconstituição injetável",
        drugInteractions: "Outros fármacos ototóxicos ou nefrotóxicos.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Estreptomicina"
      }
    ]
  },
    
  {
    name: "Esquistossomose",
    category: "negligenciada",
    causes: "Infecção causada pelo parasita *Schistosoma mansoni*, transmitido por caramujos de água doce contaminada.",
    symptoms: "Coceira, dor abdominal, diarreia, aumento do fígado e baço, sangue nas fezes.",
    treatments: "Uso de antiparasitários, tratamento das complicações hepáticas e intestinais, controle ambiental.",
    prevention: "Saneamento básico, evitar contato com águas contaminadas, controle dos caramujos vetores.",
    medicines: [
      {
        name: "Praziquantel",
        indication: "Tratamento de primeira linha da esquistossomose.",
        dosage: "40 a 60 mg/kg em dose única.",
        sideEffects: "Dor abdominal, náuseas, tontura.",
        contraindications: "Hipersensibilidade ao fármaco.",
        therapeuticAction: "Antiparasitário esquistossomicida.",
        mechanismOfAction: "Aumenta permeabilidade ao cálcio, causando paralisia do verme.",
        activeIngredient: "Praziquantel",
        dosageInstructions: "Tomar com refeição leve.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Comprimido",
        drugInteractions: "Fenitoína, carbamazepina, dexametasona.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Praziquantel"
      },
      {
        name: "Oxamniquina",
        indication: "Alternativa ao praziquantel, especialmente para cepas resistentes.",
        dosage: "15 mg/kg em dose única noturna.",
        sideEffects: "Sonolência, tontura, escurecimento da urina.",
        contraindications: "Crianças menores de 4 anos.",
        therapeuticAction: "Antiparasitário.",
        mechanismOfAction: "Causa contração muscular e separação dos vermes das paredes intestinais.",
        activeIngredient: "Oxamniquina",
        dosageInstructions: "Tomar antes de dormir.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Cápsula ou solução",
        drugInteractions: "Álcool (potencializa efeitos colaterais).",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Oxamniquina"
      },
      {
        name: "Albendazol",
        indication: "Tratamento de helmintíases associadas à esquistossomose.",
        dosage: "400 mg/dia por 3 dias.",
        sideEffects: "Dor abdominal, náuseas, cefaleia.",
        contraindications: "Gravidez, hipersensibilidade.",
        therapeuticAction: "Antiparasitário de amplo espectro.",
        mechanismOfAction: "Inibe a captação de glicose pelos vermes.",
        activeIngredient: "Albendazol",
        dosageInstructions: "Tomar com alimentos.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Comprimido",
        drugInteractions: "Cimetidina, dexametasona.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Albendazol"
      },
      {
        name: "Metronidazol",
        indication: "Tratamento de infecções intestinais associadas.",
        dosage: "500 mg 2x/dia por 5-10 dias.",
        sideEffects: "Sabor metálico, náusea, urina escurecida.",
        contraindications: "Alcoolismo ativo, doença hepática severa.",
        therapeuticAction: "Antiprotozoário e antibacteriano.",
        mechanismOfAction: "Dano ao DNA dos microrganismos.",
        activeIngredient: "Metronidazol",
        dosageInstructions: "Evitar álcool durante o uso.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Comprimido",
        drugInteractions: "Álcool, varfarina, fenitoína.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Metronidazol"
      },
      {
        name: "Prednisona",
        indication: "Tratamento de complicações inflamatórias hepatoesplênicas.",
        dosage: "20 a 60 mg/dia com desmame progressivo.",
        sideEffects: "Imunossupressão, hiperglicemia, osteoporose.",
        contraindications: "Infecção fúngica sistêmica.",
        therapeuticAction: "Corticosteroide sistêmico.",
        mechanismOfAction: "Reduz resposta inflamatória exagerada.",
        activeIngredient: "Prednisona",
        dosageInstructions: "Tomar pela manhã com alimentos.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Comprimido",
        drugInteractions: "AINEs, anticoagulantes, antidiabéticos.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Prednisona"
      }
    ]
  },
  
  {
    name: "Geo-helmintíases",
    category: "negligenciada",
    causes: "Infecções causadas por vermes intestinais como lombrigas (*Ascaris lumbricoides*), ancilostomídeos e tricurídeos.",
    symptoms: "Dor abdominal, diarreia, anemia, retardo no crescimento em crianças.",
    treatments: "Antiparasitários de amplo espectro, melhoria do saneamento básico, programas de desparasitação em massa.",
    prevention: "Lavar bem os alimentos, lavar as mãos, uso de calçados, acesso a água tratada e esgoto.",
    medicines: [
      {
        name: "Albendazol",
        indication: "Tratamento de infecções por diversos vermes intestinais.",
        dosage: "400 mg em dose única.",
        sideEffects: "Dor abdominal, náuseas, tontura.",
        contraindications: "Gravidez no 1º trimestre.",
        therapeuticAction: "Antiparasitário de amplo espectro.",
        mechanismOfAction: "Inibe absorção de glicose pelos vermes, levando à morte.",
        activeIngredient: "Albendazol",
        dosageInstructions: "Tomar com alimento.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Comprimido",
        drugInteractions: "Dexametasona, cimetidina, praziquantel.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Albendazol"
      },
      {
        name: "Mebendazol",
        indication: "Tratamento de oxiúros, lombrigas, tricurídeos.",
        dosage: "100 mg 2x/dia por 3 dias.",
        sideEffects: "Flatulência, diarreia, prurido anal.",
        contraindications: "Gravidez, hipersensibilidade.",
        therapeuticAction: "Antiparasitário.",
        mechanismOfAction: "Inibe síntese de microtúbulos dos vermes.",
        activeIngredient: "Mebendazol",
        dosageInstructions: "Tomar com alimentos.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Comprimido",
        drugInteractions: "Metronidazol (potencial neurotoxicidade).",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Mebendazol"
      },
      {
        name: "Levamisol",
        indication: "Tratamento de *Ascaris* e *Ancylostoma*.",
        dosage: "150 mg em dose única (adultos).",
        sideEffects: "Náusea, dor abdominal, tontura.",
        contraindications: "Doenças autoimunes ativas.",
        therapeuticAction: "Antiparasitário imunomodulador.",
        mechanismOfAction: "Paralisa musculatura dos vermes.",
        activeIngredient: "Levamisol",
        dosageInstructions: "Tomar à noite.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Comprimido",
        drugInteractions: "Álcool, anticoagulantes.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Levamisol"
      },
      {
        name: "Pamoato de pirantel",
        indication: "Tratamento de oxiuríase e ascaridíase.",
        dosage: "10 mg/kg (máx. 1 g), dose única.",
        sideEffects: "Dor de cabeça, distúrbios gastrointestinais.",
        contraindications: "Miastenia grave.",
        therapeuticAction: "Antiparasitário neuromuscular.",
        mechanismOfAction: "Causa paralisia espástica nos vermes.",
        activeIngredient: "Pirantel",
        dosageInstructions: "Tomar com ou sem alimentos.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Comprimido ou suspensão",
        drugInteractions: "Piperazina (efeito antagônico).",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Pirantel"
      },
      {
        name: "Ivermectina",
        indication: "Tratamento de estrongiloidíase e filariose (uso também em geo-helmintíases em massa).",
        dosage: "150 a 200 mcg/kg, dose única.",
        sideEffects: "Coceira, tontura, dor muscular.",
        contraindications: "Gestantes, crianças < 15 kg.",
        therapeuticAction: "Antiparasitário sistêmico.",
        mechanismOfAction: "Age nos canais de cloro controlados pelo glutamato do parasita.",
        activeIngredient: "Ivermectina",
        dosageInstructions: "Tomar em jejum.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Comprimido",
        drugInteractions: "Outros antiparasitários e sedativos.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Ivermectina"
      }
    ]
  },  

  {
    name: "Filariose",
    category: "negligenciada",
    causes: "Infecção causada por vermes do gênero *Wuchereria bancrofti*, transmitidos por picadas de mosquitos.",
    symptoms: "Inchaço crônico dos membros (elefantíase), febre, dor e inflamação dos linfonodos e vasos linfáticos.",
    treatments: "Medicamentos antiparasitários, tratamento das infecções secundárias, controle de vetores e cuidados com a pele.",
    prevention: "Uso de mosquiteiros, controle de vetores, programas de desparasitação em massa.",
    medicines: [
      {
        name: "Dietilcarbamazina (DEC)",
        indication: "Tratamento da filariose linfática.",
        dosage: "6 mg/kg/dia por 12 dias.",
        sideEffects: "Febre, dor de cabeça, reações inflamatórias (Mazzotti).",
        contraindications: "Gravidez, alergia à substância.",
        therapeuticAction: "Antiparasitário microfilaricida.",
        mechanismOfAction: "Paralisa os vermes e facilita sua destruição pelo sistema imune.",
        activeIngredient: "Dietilcarbamazina",
        dosageInstructions: "Tomar após refeição para reduzir irritação gástrica.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Comprimido",
        drugInteractions: "Corticosteroides para controle de reação inflamatória.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Dietilcarbamazina"
      },
      {
        name: "Ivermectina",
        indication: "Tratamento de filariose e outras helmintíases.",
        dosage: "150 a 200 mcg/kg em dose única anual (em massa).",
        sideEffects: "Prurido, tontura, dor muscular.",
        contraindications: "Gestação, crianças < 15 kg.",
        therapeuticAction: "Antiparasitário sistêmico.",
        mechanismOfAction: "Bloqueia transmissão neuromuscular do parasita.",
        activeIngredient: "Ivermectina",
        dosageInstructions: "Tomar em jejum.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Comprimido",
        drugInteractions: "Sedativos, outros antiparasitários.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Ivermectina"
      },
      {
        name: "Albendazol",
        indication: "Uso em combinação para eliminação de vermes adultos.",
        dosage: "400 mg dose única.",
        sideEffects: "Dor abdominal, tontura.",
        contraindications: "Gravidez no 1º trimestre.",
        therapeuticAction: "Antiparasitário de amplo espectro.",
        mechanismOfAction: "Inibe absorção de glicose dos vermes.",
        activeIngredient: "Albendazol",
        dosageInstructions: "Tomar com alimento.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Comprimido",
        drugInteractions: "Dexametasona, cimetidina.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Albendazol"
      },
      {
        name: "Doxiciclina",
        indication: "Tratamento auxiliar visando matar bactérias simbióticas (*Wolbachia*) da filária.",
        dosage: "100 mg 2x/dia por 4 a 6 semanas.",
        sideEffects: "Fotossensibilidade, náuseas.",
        contraindications: "Gravidez, crianças < 8 anos.",
        therapeuticAction: "Antibiótico tetraciclina.",
        mechanismOfAction: "Mata bactérias simbióticas essenciais para os parasitas.",
        activeIngredient: "Doxiciclina",
        dosageInstructions: "Evitar sol e tomar com bastante água.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Comprimido",
        drugInteractions: "Antiácidos, retinoides.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Doxiciclina"
      },
      {
        name: "Prednisona",
        indication: "Controle de reações inflamatórias após morte dos parasitas.",
        dosage: "20–60 mg/dia com desmame gradual.",
        sideEffects: "Aumento de apetite, retenção de líquidos, imunossupressão.",
        contraindications: "Infecção fúngica sistêmica.",
        therapeuticAction: "Corticosteroide anti-inflamatório.",
        mechanismOfAction: "Inibe resposta inflamatória exacerbada.",
        activeIngredient: "Prednisona",
        dosageInstructions: "Tomar pela manhã com alimentos.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Comprimido",
        drugInteractions: "AINEs, anticoagulantes, antidiabéticos.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Prednisona"
      }
    ]
  },  
  
  {
    name: "Leishmaniose Visceral",
    category: "negligenciada",
    causes: "Infecção por protozoário *Leishmania chagasi* (ou *L. infantum*), transmitido pela picada do mosquito-palha.",
    symptoms: "Febre prolongada, emagrecimento, aumento do baço e fígado, anemia, fraqueza.",
    treatments: "Uso de medicamentos específicos antileishmania, internação em casos graves e tratamento de suporte.",
    prevention: "Controle do vetor, uso de repelentes, tratamento de cães infectados, limpeza de ambientes.",
    medicines: [
      {
        name: "Antimoniato de meglumina (Glucantime®)",
        indication: "Tratamento de primeira linha da leishmaniose visceral.",
        dosage: "20 mg Sb⁵/kg/dia por 20 a 30 dias.",
        sideEffects: "Dor no local da aplicação, náuseas, toxicidade hepática e cardíaca.",
        contraindications: "Doenças cardíacas, hepáticas ou renais graves.",
        therapeuticAction: "Antiprotozoário pentavalente.",
        mechanismOfAction: "Inibe enzimas essenciais ao metabolismo do parasita.",
        activeIngredient: "Antimoniato de meglumina",
        dosageInstructions: "Aplicação sob supervisão médica.",
        administrationRoute: "Intramuscular ou intravenosa",
        pharmaceuticalForm: "Solução injetável",
        drugInteractions: "Outros medicamentos hepatotóxicos e nefrotóxicos.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Glucantime"
      },
      {
        name: "Anfotericina B lipossomal",
        indication: "Tratamento de segunda linha ou para pacientes graves.",
        dosage: "3 mg/kg/dia por 5 a 10 dias.",
        sideEffects: "Febre, calafrios, toxicidade renal.",
        contraindications: "Alergia à anfotericina.",
        therapeuticAction: "Antifúngico com ação antiparasitária.",
        mechanismOfAction: "Altera a permeabilidade da membrana do parasita.",
        activeIngredient: "Anfotericina B",
        dosageInstructions: "Aplicar lentamente em ambiente hospitalar.",
        administrationRoute: "Intravenosa",
        pharmaceuticalForm: "Solução injetável",
        drugInteractions: "Aminoglicosídeos, ciclosporina, nefrotóxicos.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Ambisome"
      },
      {
        name: "Miltefosina",
        indication: "Alternativa oral para tratamento da leishmaniose visceral.",
        dosage: "2,5 mg/kg/dia por 28 dias.",
        sideEffects: "Distúrbios gastrointestinais, toxicidade hepática.",
        contraindications: "Gravidez, doenças renais ou hepáticas graves.",
        therapeuticAction: "Antileishmania oral.",
        mechanismOfAction: "Afeta a membrana celular e a sinalização do parasita.",
        activeIngredient: "Miltefosina",
        dosageInstructions: "Tomar com alimentos.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Cápsula",
        drugInteractions: "Outros hepatotóxicos.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Miltefosina"
      },
      {
        name: "Pentamidina",
        indication: "Uso em casos refratários de leishmaniose.",
        dosage: "4 mg/kg em dias alternados, por 15 a 30 dias.",
        sideEffects: "Hipoglicemia, toxicidade renal, hipotensão.",
        contraindications: "Gravidez, insuficiência renal.",
        therapeuticAction: "Antiprotozoário sistêmico.",
        mechanismOfAction: "Afeta DNA e metabolismo energético do parasita.",
        activeIngredient: "Pentamidina isetionato",
        dosageInstructions: "Uso exclusivamente hospitalar.",
        administrationRoute: "Intramuscular ou intravenosa",
        pharmaceuticalForm: "Solução injetável",
        drugInteractions: "Outros nefrotóxicos ou hipoglicemiantes.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Pentamidina"
      },
      {
        name: "Prednisona",
        indication: "Tratamento de reações inflamatórias secundárias à lise parasitária.",
        dosage: "20 a 60 mg/dia com redução gradual.",
        sideEffects: "Aumento de glicemia, insônia, imunossupressão.",
        contraindications: "Infecções fúngicas sistêmicas.",
        therapeuticAction: "Corticosteroide anti-inflamatório.",
        mechanismOfAction: "Modula resposta imune e reduz inflamação.",
        activeIngredient: "Prednisona",
        dosageInstructions: "Tomar de manhã com alimentos.",
        administrationRoute: "Oral",
        pharmaceuticalForm: "Comprimido",
        drugInteractions: "Anticoagulantes, AINEs, antidiabéticos.",
        leafletAnvisaUrl: "https://consultas.anvisa.gov.br/#/bulario/q/?nomeProduto=Prednisona"
      }
    ]
  },
        
];
